spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://182.61.23.57:3308/jd_jklc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: QjhsmF26m7wsCrIz
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true


# 短信
smsnational:
   urlGL: http://smssh1.253.com/msg/send/json
   accountGL: N0127464
   passwordGL: FgYURl6sqC45bb
   urlGW: http://intapi.253.com/send/json
   accountGW: I1674626
   passwordGW: Buwtzaq6nVe2ee
   signEN: KEBE

qiniuyun:
  ACCESS_KEY: 6ctFbKBnYX3aug1mLT37EzaMM9ruN83_iql2QJTk
  SECRET_KEY: NCfqpam6v4aWLKO75rPK0XNmkymEL49EVjLDagpp
  BUCKET: gkpay
  callbackUrl: http://182.61.23.57:9093/damo-api/api/qiniuyunController/callback

woPay:
    merchantId: newpay
    secretKey: zpaQA25XcK75nMN82kYcKg==
    callBackUrl: http://182.61.23.57:9090/damo-api/api/woPay/callBack
#商城地址
mall:
    url: http://127.0.0.1:9050/new-mall-api